### ISSUE TITLE
problem post install

### ISSUE THREAD

**Issue by gronimo** [Compizfox/RadiusAdmin#3]
Hi, first time i navigate on the web interface,  i have the folowing error:

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/app/classes/BasePageidFinder.php on line 38

I don't know what to do for the moment,

Thanks to reply

**Comment by Compizfox** [comment]
Hi,

See #1. This happens because your PHP is out of date. PHP7 is required for the latest versions.

**Comment by Compizfox** [comment]
> Thanks for the reply, infact i have setup phpv7 but apache doesn't use it by default if php 5 is already installed. So i have disable the apache's mod_php and enable the mod php7.0.
> And it works!

Great to hear :)
